# Part 1

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np
%pylab inline

Populating the interactive namespace from numpy and matplotlib

Read all spreadsheets from GitHub repo

In [2]:
##Australia
aus_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20AUSTRALIA%20CHART%20-%20TOP%20200%20(2019-03-17).csv')
aus_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20AUSTRALIA%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

##Canada
can_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20CANADA%20CHART%20-%20TOP%20200%20(2019-03-17).csv')
can_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20CANADA%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

##Global
global_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20GLOBAL%20CHART%20-%20TOP%20200%20(2019-03-18).csv')
global_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20GLOBAL%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

##Ireland
ireland_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20IRELAND%20CHART%20-%20TOP%20200%20(2019-03-17).csv')
ireland_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20IRELAND%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

##New Zealand
nz_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20NEW%20ZEALAND%20CHART%20-%20TOP%20200%20(2019-03-17).csv')
nz_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20NEW%20ZEALAND%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

##United Kingdom
uk_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20UNITED%20KINGDOM%20CHART%20-%20TOP%20200%20(2019-03-18).csv')
uk_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20UNITED%20KINGDOM%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

##United States
us_200 = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20UNITED%20STATES%20CHART%20-%20TOP%20200%20(2019-03-18).csv')
us_viral = pd.read_csv('https://raw.githubusercontent.com/elahshalev/interview_test/master/spotify_top200_viral50_data/SPOTIFY%20DAILY%20UNITED%20STATES%20CHART%20-%20VIRAL%2050%20(2019-03-17).csv')

Concatenate all spreadsheets

In [3]:
##put all spreadsheets (dfs) into a list
spreadsheets = [aus_200, aus_viral, can_200, can_viral, global_200, global_viral, ireland_200, ireland_viral, nz_200, nz_viral, uk_200, uk_viral, us_200, us_viral]

##concatinate to create new df
df = pd.concat(spreadsheets, sort = True)

Drop columns

In [4]:
df = df.drop(columns=['Album(s)', 'UPC', 'Latest Charting Date', 'Spotify Track Link', 'Spotify Artist Link', 'Spotify Album Link', 'Chart Cycle' ])

##Show remaining columns in new df
df.columns.values

array(['Artist(s)', 'Chart Type', 'Country', 'Days on Chart',
       'Historical Positions', 'ISRC', 'Latest Position', 'Peak Date',
       'Peak Position', 'Position Change', 'Record Label', 'Release Date',
       'Spotify Album Ids', 'Spotify Artist Id(s)', 'Spotify Track Ids',
       'Streams', 'Track'], dtype=object)

Rename columns

In [5]:
df = df.rename(columns={'Track':'track', 'ISRC':'isrc', 'Spotify Track Ids':'track_id', 'Artist(s)':'artist', 'Spotify Artist Id(s)':'artist_id', 'Spotify Album Ids':'album_id', 'Release Date': 'r_date', 'Record Label' : 'label', 'Country':'country', 'Days on Chart':'days_chart', 'Chart Type':'chart_type', 'Peak Position':'peak_pos', 'Peak Date':'peak_date', 'Latest Position':'latest_pos', 'Position Change':'pos_chg', 'Historical Positions':'hist_pos'})

##Show new columns names
df.columns.values

array(['artist', 'chart_type', 'country', 'days_chart', 'hist_pos',
       'isrc', 'latest_pos', 'peak_date', 'peak_pos', 'pos_chg', 'label',
       'r_date', 'album_id', 'artist_id', 'track_id', 'Streams', 'track'],
      dtype=object)

Convert all values in 'artist' and 'track' columns are strings

In [6]:
df['artist'] = df['artist'].astype(str)
df['track'] = df['track'].astype(str) 

df.dtypes

artist         object
chart_type     object
country        object
days_chart      int64
hist_pos       object
isrc           object
latest_pos      int64
peak_date      object
peak_pos        int64
pos_chg       float64
label          object
r_date         object
album_id       object
artist_id      object
track_id       object
Streams       float64
track          object
dtype: object

Fill NULL values in 'label' columns with 'UNKNOWN'

In [7]:
df['label'] = df['label'].fillna('UNKNOWN')

##Amount of vaues where label has been changed to UNKNOWN
len(df[df['label'] == 'UNKNOWN'])

36

In [8]:
##Function to take value from historical position and find second to last item
def calc_prev_pos(hist_pos):
    values = hist_pos.split(', ')
        
    if len(values) == 1:
        prev_pos = values[0]
        
    else:
        prev_pos = values[-2]
    
    prev_pos = int(prev_pos)
    
    return prev_pos

In [9]:
##apply function to hist_pos column
df['prev_pos'] = df['hist_pos'].apply(calc_prev_pos)
df[['hist_pos','prev_pos']][:10]

                                            hist_pos  prev_pos
0  59, 22, 8, 6, 6, 6, 6, 5, 5, 1, 1, 1, 1, 1, 1,...         1
1  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...         2
2  48, 5, 4, 4, 4, 4, 5, 4, 4, 4, 2, 2, 3, 2, 2, ...         4
3  2, 2, 1, 1, 1, 1, 2, 15, 14, 1, 1, 1, 1, 1, 2,...         3
4  5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2...         5
5  59, 44, 30, 11, 8, 8, 8, 6, 6, 6, 6, 6, 6, 6, ...         6
6  111, 114, 114, 85, 56, 51, 50, 50, 44, 40, 38,...         7
7  194, 124, 112, 133, 138, 145, 154, 133, 98, 92...         8
8        121, 7, 7, 7, 6, 7, 7, 7, 7, 7, 8, 8, 10, 9        10
9             27, 25, 19, 19, 15, 15, 12, 12, 12, 10        12

In [10]:
##column that calculates difference between previous and current position
df['pos_chg'] = (df['latest_pos'] - df['prev_pos'])
df[:5]

,artist,chart_type,country,days_chart,hist_pos,isrc,latest_pos,peak_date,peak_pos,pos_chg,label,r_date,album_id,artist_id,track_id,Streams,track,prev_pos
0,Jonas Brothers,regional,Australia,18,"59, 22, 8, 6, 6, 6, 6, 5, 5, 1, 1, 1, 1, 1, 1,...",USUG11900515,1,2019-03-09,1,0,Jonas Brothers Recording,2019-02-28,4W0r9HOcuCC6Vh7aze2hwi,7gOdHgIoIKoe4i9Tta6qdD,4y3OI86AEP6PQoDE6olYhO,229842.0,Sucker,1
1,Ariana Grande,regional,Australia,39,"1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...",USUM71900110,2,2019-02-07,1,0,Republic Records,2019-02-07,2fYhqwDWXjbpjaIJPEfKFw,66CXWjxzNUsdJxJ2JdwvnR,6ocbgoVGwYJhOv1GgI9NsF,185709.0,7 rings,2
2,Post Malone,regional,Australia,84,"48, 5, 4, 4, 4, 4, 5, 4, 4, 4, 2, 2, 3, 2, 2, ...",USUM71822626,3,2019-01-03,2,-1,Republic Records,2018-12-23,5Dcz8PZHKuvTyjbqEPL5VM,246dkjvS1zLTtiykXe5h60,6MWtB6iiXyIwun0YzU6DFP,184795.0,Wow.,4
3,"Post Malone, Swae Lee",regional,Australia,77,"2, 2, 1, 1, 1, 1, 2, 15, 14, 1, 1, 1, 1, 1, 2,...",USUM71814888,4,2018-12-18,1,1,Universal Records,2018-12-13,35s58BRTGAEWztPo9WqCIs,"246dkjvS1zLTtiykXe5h60, 1zNqQNIdeOUZHb8zbZRFMX",3KkXRkHbMCARz0aVfEt68P,181311.0,Sunflower - Spider-Man: Into the Spider-Verse,3
4,Ariana Grande,regional,Australia,39,"5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2...",USUM71900409,5,2019-02-08,2,0,Republic Records,2019-02-07,2fYhqwDWXjbpjaIJPEfKFw,66CXWjxzNUsdJxJ2JdwvnR,4kV4N9D1iKVxx1KLvtTpjS,175075.0,"break up with your girlfriend, i'm bored",5

Import off limits artist and label spreadsheets

In [11]:
ollabels = pd.read_excel('off_limits_labels.xlsx', dtype=object)
olartists = pd.read_excel('off_limits_artists.xlsx', dtype=object)

Create new columns where all values are uppercase in dataframe and off limits values

In [12]:
##function to make specific column uppercase
def col_upper(dataframe, upper_column, column):
    dataframe[upper_column] = dataframe[column].str.upper()

##uppercase off limits labels
col_upper(ollabels, 'label_upper', 'label')

##uppercase off limits artists
col_upper(olartists, 'artist_upper', 'artist')

##uppercase artist and label names in dataframe
col_upper(df, 'label_upper', 'label')
col_upper(df, 'artist_upper', 'artist')

df[:5]

,artist,chart_type,country,days_chart,hist_pos,isrc,latest_pos,peak_date,peak_pos,pos_chg,label,r_date,album_id,artist_id,track_id,Streams,track,prev_pos,label_upper,artist_upper
0,Jonas Brothers,regional,Australia,18,"59, 22, 8, 6, 6, 6, 6, 5, 5, 1, 1, 1, 1, 1, 1,...",USUG11900515,1,2019-03-09,1,0,Jonas Brothers Recording,2019-02-28,4W0r9HOcuCC6Vh7aze2hwi,7gOdHgIoIKoe4i9Tta6qdD,4y3OI86AEP6PQoDE6olYhO,229842.0,Sucker,1,JONAS BROTHERS RECORDING,JONAS BROTHERS
1,Ariana Grande,regional,Australia,39,"1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...",USUM71900110,2,2019-02-07,1,0,Republic Records,2019-02-07,2fYhqwDWXjbpjaIJPEfKFw,66CXWjxzNUsdJxJ2JdwvnR,6ocbgoVGwYJhOv1GgI9NsF,185709.0,7 rings,2,REPUBLIC RECORDS,ARIANA GRANDE
2,Post Malone,regional,Australia,84,"48, 5, 4, 4, 4, 4, 5, 4, 4, 4, 2, 2, 3, 2, 2, ...",USUM71822626,3,2019-01-03,2,-1,Republic Records,2018-12-23,5Dcz8PZHKuvTyjbqEPL5VM,246dkjvS1zLTtiykXe5h60,6MWtB6iiXyIwun0YzU6DFP,184795.0,Wow.,4,REPUBLIC RECORDS,POST MALONE
3,"Post Malone, Swae Lee",regional,Australia,77,"2, 2, 1, 1, 1, 1, 2, 15, 14, 1, 1, 1, 1, 1, 2,...",USUM71814888,4,2018-12-18,1,1,Universal Records,2018-12-13,35s58BRTGAEWztPo9WqCIs,"246dkjvS1zLTtiykXe5h60, 1zNqQNIdeOUZHb8zbZRFMX",3KkXRkHbMCARz0aVfEt68P,181311.0,Sunflower - Spider-Man: Into the Spider-Verse,3,UNIVERSAL RECORDS,"POST MALONE, SWAE LEE"
4,Ariana Grande,regional,Australia,39,"5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2...",USUM71900409,5,2019-02-08,2,0,Republic Records,2019-02-07,2fYhqwDWXjbpjaIJPEfKFw,66CXWjxzNUsdJxJ2JdwvnR,4kV4N9D1iKVxx1KLvtTpjS,175075.0,"break up with your girlfriend, i'm bored",5,REPUBLIC RECORDS,ARIANA GRANDE

Compare values in dataframe to off limits values

In [13]:
##function to create list of values in off limits df
def create_list(dataframe, column):
    value_list = dataframe[column].values.tolist()
    
    return value_list

##create the off limits lists of values
artist_list = create_list(olartists, 'artist_upper')
label_list = create_list(ollabels, 'label_upper')

In [14]:
##remove values that are in the off limits lists
def remove_off_limits(dataframe, value_list, upper_col):
    ##Only keep values not in the off limits list
    dataframe = dataframe[dataframe[upper_col].isin(value_list) == False]
    
    return dataframe

df = remove_off_limits(df, artist_list, 'artist_upper')
df = remove_off_limits(df, label_list, 'label_upper')

print 'Remaining rows in dataframe: ', len(df)

Remaining rows in dataframe:  173

/Users/elahshalev/anaconda2/lib/python2.7/site-packages/pandas/core/algorithms.py:421: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  f = lambda x, y: htable.ismember_object(x, values)

In [15]:
##drop uppercase columns
df = df.drop(columns = ['artist_upper', 'label_upper'])
print 'Remaining columns: ', df.columns.values

Remaining columns:  ['artist' 'chart_type' 'country' 'days_chart' 'hist_pos' 'isrc'
 'latest_pos' 'peak_date' 'peak_pos' 'pos_chg' 'label' 'r_date' 'album_id'
 'artist_id' 'track_id' 'Streams' 'track' 'prev_pos']

Create artist frequency column

In [16]:
#Create new column with counts
df['freq'] = df.groupby(['artist'])['artist_id'].transform('count')
df[:5]

,artist,chart_type,country,days_chart,hist_pos,isrc,latest_pos,peak_date,peak_pos,pos_chg,label,r_date,album_id,artist_id,track_id,Streams,track,prev_pos,freq
39,Ocean Alley,regional,Australia,138,"117, 146, 154, 147, 132, 135, 147, 169, 185, 1...",AUZN31700127,40,2019-01-27,4,0,Ocean Alley,2018-03-08,0MVMsDS0kofp6A8cbJ5kSH,18lpwfiys4GtdHWNUu9qQr,7to68V64Cu6zk0UDo5tyw3,81772.0,Confidence,40,3
49,"Billie Eilish, Khalid",regional,Australia,102,"45, 43, 40, 40, 38, 36, 37, 46, 50, 47, 46, 48...",USUM71804190,50,2019-02-05,29,-1,Darkroom,2017-08-10,5YCdlD3eREt72lTZxNL7id,"6qqNVTkY8uBg9cP3Jd7DAH, 6LuN9FCkKOj5PcnpouEgny",1NJcg626wLln4pGHpiV7mf,68852.0,lovely - Bonus Track,51,7
97,The Killers,regional,Australia,985,"112, 115, 115, 135, 121, 121, 128, 124, 134, 1...",USIR20400274,98,2017-12-30,47,11,"Universal, Island Def Jam",2003-12-31,4undIeGmofnAYKhnDclN1w,0C0XlULifJtAgn6ZNCW2eu,7oK9VyNzrYvRFo7nQEYkWN,42098.0,Mr. Brightside,87,6
101,King Princess,regional,Australia,365,"149, 87, 86, 88, 100, 86, 84, 57, 57, 58, 66, ...",USSM11801303,102,2018-05-19,13,-28,"Zelig Records, Columbia Records",2018-02-22,5p0UaZsYWMn4L1dSpc6AhN,6beUvFUlKliUYJdLOXNj9C,0CZ8lquoTX2Dkg7Ak2inwA,41399.0,1950,130,2
112,"A$AP Rocky, Skepta",regional,Australia,297,"30, 36, 32, 32, 33, 34, 33, 36, 46, 46, 44, 42...",USRC11800930,113,2018-06-07,24,8,"A$AP Worldwide, Polo Grounds Music, RCA Records",2018-05-24,3MATDdrpHmQCmuOcozZjDa,"13ubrt8QOOCPljQ2FL1Kca, 2p1fiYHYiXz9qi0JJyxBzN",7ycWLEP1GsNjVvcjawXz3z,39285.0,Praise The Lord (Da Shine),105,6

Reorder columns

In [17]:
df = df[['artist', 
'track', 
'r_date', 
'label', 
'country', 
'chart_type',
'latest_pos',
'days_chart', 
'freq', 
'peak_pos', 
'peak_date', 
'pos_chg', 
'hist_pos',  
'track_id', 
'artist_id', 
'album_id', 
'isrc']]
df[:5]

,artist,track,r_date,label,country,chart_type,latest_pos,days_chart,freq,peak_pos,peak_date,pos_chg,hist_pos,track_id,artist_id,album_id,isrc
39,Ocean Alley,Confidence,2018-03-08,Ocean Alley,Australia,regional,40,138,3,4,2019-01-27,0,"117, 146, 154, 147, 132, 135, 147, 169, 185, 1...",7to68V64Cu6zk0UDo5tyw3,18lpwfiys4GtdHWNUu9qQr,0MVMsDS0kofp6A8cbJ5kSH,AUZN31700127
49,"Billie Eilish, Khalid",lovely - Bonus Track,2017-08-10,Darkroom,Australia,regional,50,102,7,29,2019-02-05,-1,"45, 43, 40, 40, 38, 36, 37, 46, 50, 47, 46, 48...",1NJcg626wLln4pGHpiV7mf,"6qqNVTkY8uBg9cP3Jd7DAH, 6LuN9FCkKOj5PcnpouEgny",5YCdlD3eREt72lTZxNL7id,USUM71804190
97,The Killers,Mr. Brightside,2003-12-31,"Universal, Island Def Jam",Australia,regional,98,985,6,47,2017-12-30,11,"112, 115, 115, 135, 121, 121, 128, 124, 134, 1...",7oK9VyNzrYvRFo7nQEYkWN,0C0XlULifJtAgn6ZNCW2eu,4undIeGmofnAYKhnDclN1w,USIR20400274
101,King Princess,1950,2018-02-22,"Zelig Records, Columbia Records",Australia,regional,102,365,2,13,2018-05-19,-28,"149, 87, 86, 88, 100, 86, 84, 57, 57, 58, 66, ...",0CZ8lquoTX2Dkg7Ak2inwA,6beUvFUlKliUYJdLOXNj9C,5p0UaZsYWMn4L1dSpc6AhN,USSM11801303
112,"A$AP Rocky, Skepta",Praise The Lord (Da Shine),2018-05-24,"A$AP Worldwide, Polo Grounds Music, RCA Records",Australia,regional,113,297,6,24,2018-06-07,8,"30, 36, 32, 32, 33, 34, 33, 36, 46, 46, 44, 42...",7ycWLEP1GsNjVvcjawXz3z,"13ubrt8QOOCPljQ2FL1Kca, 2p1fiYHYiXz9qi0JJyxBzN",3MATDdrpHmQCmuOcozZjDa,USRC11800930

# Part 2

Scraping script for Spotify API

In [18]:
##clone dataframe to do Spotify API analysis
dfs = df
dfs[:1]

,artist,track,r_date,label,country,chart_type,latest_pos,days_chart,freq,peak_pos,peak_date,pos_chg,hist_pos,track_id,artist_id,album_id,isrc
39,Ocean Alley,Confidence,2018-03-08,Ocean Alley,Australia,regional,40,138,3,4,2019-01-27,0,"117, 146, 154, 147, 132, 135, 147, 169, 185, 1...",7to68V64Cu6zk0UDo5tyw3,18lpwfiys4GtdHWNUu9qQr,0MVMsDS0kofp6A8cbJ5kSH,AUZN31700127

In [19]:
##install spotipy - python library for Spotify API
! pip install spotipy

Requirement already satisfied: spotipy in ./anaconda2/lib/python2.7/site-packages (2.4.4)
Requirement already satisfied: requests>=1.0 in ./anaconda2/lib/python2.7/site-packages (from spotipy) (2.21.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda2/lib/python2.7/site-packages (from requests>=1.0->spotipy) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda2/lib/python2.7/site-packages (from requests>=1.0->spotipy) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda2/lib/python2.7/site-packages (from requests>=1.0->spotipy) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in ./anaconda2/lib/python2.7/site-packages (from requests>=1.0->spotipy) (1.24.1)

In [20]:
import sys
import spotipy
import spotipy.util as util

With each track_id, obtain the track_uri, song popularity score, and release_date.

In [21]:
##define all parameters for method
state = 'user-follow-read playlist-modify-public'

USERNAME = 'elahshalev0000'
SCOPE = state
CLIENT_ID = 'e1c36ae34b754343a4d37ba55dae3d9f'
CLIENT_SECRET = 'e728a736740e435cb99f669141b20ebf'
REDIRECT = 'http://localhost/'

##authorize app
token = util.prompt_for_user_token(USERNAME, SCOPE, CLIENT_ID, CLIENT_SECRET, REDIRECT)

sp = spotipy.Spotify(auth = token)

In [22]:
##function to find popularity
def find_pop(track):
    track = sp.track(track)
    pop = track['popularity']
    
    return pop
    
##function to find uri    
def find_track_uri(track):
    track = sp.track(track)
    uri = track['uri']
    
    return uri
    

##function to find release date
def find_release_date(track):
    track = sp.track(track)
    
    ##release date from album
    album = track['album']
    release_date = album['release_date']
        
    return release_date

In [23]:
##for each track find label/distributor
def find_label(track_id):
    track = sp.track(track_id)
    album = track['album']
    album_id = album['id']

    album = sp.album(album_id)
    label = album['label']
    
    return label

In [24]:
##function to find artists popularity score
def find_artist_popularity(track_id):
    track = sp.track(track_id)
    
    ##get list of artists on track
    artists = track['artists']
    
    ##empty list for artist ids
    artist_ids = []
    
    ##find artist id for each artist in list
    for artist in artists:
        a_id = artist['id']
        
        ##add id to list
        artist_ids.append(a_id)
    
    ##empty list of popularity
    artist_popularities = []
    
    ##look up each artist by id and find popularity
    for a_id in artist_ids:
        artist = sp.artist(a_id)
        popularity = artist['popularity']
        
        ##add to list of popularity scores
        artist_popularities.append(popularity)
    
    return artist_popularities

# Getting values from Spotify API

In [25]:
track_id_list = dfs['track_id'].tolist()

##create empty dataframe to store new values from API
dff = pd.DataFrame()

##Set values for track id in new df
dff['track_id'] = dfs['track_id']

In [26]:
##empty list for song popularity scores
popularity_score_list = []

##for each track find the popularity score from API
for track_id in track_id_list:
    popularity_score = find_pop(track_id)
    popularity_score_list.append(popularity_score)

##Make the scores into a series
popularity_score_series = pd.Series(popularity_score_list)

##add to new df
dff['popularity_score'] = popularity_score_series

dff[:5]

                   track_id  popularity_score
39   7to68V64Cu6zk0UDo5tyw3              69.0
49   1NJcg626wLln4pGHpiV7mf              82.0
97   7oK9VyNzrYvRFo7nQEYkWN              50.0
101  0CZ8lquoTX2Dkg7Ak2inwA              69.0
112  7ycWLEP1GsNjVvcjawXz3z              49.0

In [27]:
track_uri_list = []

for track_id in track_id_list:
    track_uri = find_track_uri(track_id)
    track_uri_list.append(track_uri)

track_uri_series = pd.Series(track_uri_list)

dff['track_uri'] = track_uri_series
dff[:5]

,track_id,popularity_score,track_uri
39,7to68V64Cu6zk0UDo5tyw3,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX
49,1NJcg626wLln4pGHpiV7mf,82.0,spotify:track:7ef4DlsgrMEH11cDZd32M6
97,7oK9VyNzrYvRFo7nQEYkWN,50.0,spotify:track:1UzofFX5AkfTDnwjcBkM4J
101,0CZ8lquoTX2Dkg7Ak2inwA,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX
112,7ycWLEP1GsNjVvcjawXz3z,49.0,spotify:track:5YOqfElMeshCt5oRk4yAgx

In [28]:
release_date_list = []

for track_id in track_id_list:
    release_date = find_release_date(track_id)
    release_date_list.append(release_date)

release_date_series = pd.Series(release_date_list)

dff['release_date'] = release_date_series
dff[:5]

,track_id,popularity_score,track_uri,release_date
39,7to68V64Cu6zk0UDo5tyw3,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX,2018-12-11
49,1NJcg626wLln4pGHpiV7mf,82.0,spotify:track:7ef4DlsgrMEH11cDZd32M6,2018-04-06
97,7oK9VyNzrYvRFo7nQEYkWN,50.0,spotify:track:1UzofFX5AkfTDnwjcBkM4J,2002
101,0CZ8lquoTX2Dkg7Ak2inwA,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX,2018-12-11
112,7ycWLEP1GsNjVvcjawXz3z,49.0,spotify:track:5YOqfElMeshCt5oRk4yAgx,2017-11-17

In [29]:
label_list = []

for track_id in track_id_list:
    label = find_label(track_id)
    label_list.append(label)

label_series = pd.Series(label_list)

dff['label'] = label_series
dff[:5]

,track_id,popularity_score,track_uri,release_date,label
39,7to68V64Cu6zk0UDo5tyw3,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX,2018-12-11,Oat Milk
49,1NJcg626wLln4pGHpiV7mf,82.0,spotify:track:7ef4DlsgrMEH11cDZd32M6,2018-04-06,Sony Music UK
97,7oK9VyNzrYvRFo7nQEYkWN,50.0,spotify:track:1UzofFX5AkfTDnwjcBkM4J,2002,Epic/Legacy
101,0CZ8lquoTX2Dkg7Ak2inwA,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX,2018-12-11,Oat Milk
112,7ycWLEP1GsNjVvcjawXz3z,49.0,spotify:track:5YOqfElMeshCt5oRk4yAgx,2017-11-17,Universal Music New Zealand Limited

In [30]:
artist_pop_list = []

for track_id in track_id_list:
    artist_pop = find_artist_popularity(track_id)
    artist_pop_list.append(artist_pop)

artist_pop_series = pd.Series(artist_pop_list)

dff['artist_popularity'] = artist_pop_series
dff[:5]

,track_id,popularity_score,track_uri,release_date,label,artist_popularity
39,7to68V64Cu6zk0UDo5tyw3,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX,2018-12-11,Oat Milk,[72]
49,1NJcg626wLln4pGHpiV7mf,82.0,spotify:track:7ef4DlsgrMEH11cDZd32M6,2018-04-06,Sony Music UK,"[89, 87]"
97,7oK9VyNzrYvRFo7nQEYkWN,50.0,spotify:track:1UzofFX5AkfTDnwjcBkM4J,2002,Epic/Legacy,[59]
101,0CZ8lquoTX2Dkg7Ak2inwA,69.0,spotify:track:67EUBsc4qosGOVbaYy6TeX,2018-12-11,Oat Milk,[72]
112,7ycWLEP1GsNjVvcjawXz3z,49.0,spotify:track:5YOqfElMeshCt5oRk4yAgx,2017-11-17,Universal Music New Zealand Limited,[62]

# Populating dataframe

In [31]:
##replace all existing values in df with new values
dfs['release_date'] = dff['release_date']
dfs['label'] = dff['label']

dfs[:5]

,artist,track,r_date,label,country,chart_type,latest_pos,days_chart,freq,peak_pos,peak_date,pos_chg,hist_pos,track_id,artist_id,album_id,isrc,release_date
39,Ocean Alley,Confidence,2018-03-08,Oat Milk,Australia,regional,40,138,3,4,2019-01-27,0,"117, 146, 154, 147, 132, 135, 147, 169, 185, 1...",7to68V64Cu6zk0UDo5tyw3,18lpwfiys4GtdHWNUu9qQr,0MVMsDS0kofp6A8cbJ5kSH,AUZN31700127,2018-12-11
49,"Billie Eilish, Khalid",lovely - Bonus Track,2017-08-10,Sony Music UK,Australia,regional,50,102,7,29,2019-02-05,-1,"45, 43, 40, 40, 38, 36, 37, 46, 50, 47, 46, 48...",1NJcg626wLln4pGHpiV7mf,"6qqNVTkY8uBg9cP3Jd7DAH, 6LuN9FCkKOj5PcnpouEgny",5YCdlD3eREt72lTZxNL7id,USUM71804190,2018-04-06
97,The Killers,Mr. Brightside,2003-12-31,Epic/Legacy,Australia,regional,98,985,6,47,2017-12-30,11,"112, 115, 115, 135, 121, 121, 128, 124, 134, 1...",7oK9VyNzrYvRFo7nQEYkWN,0C0XlULifJtAgn6ZNCW2eu,4undIeGmofnAYKhnDclN1w,USIR20400274,2002
101,King Princess,1950,2018-02-22,Oat Milk,Australia,regional,102,365,2,13,2018-05-19,-28,"149, 87, 86, 88, 100, 86, 84, 57, 57, 58, 66, ...",0CZ8lquoTX2Dkg7Ak2inwA,6beUvFUlKliUYJdLOXNj9C,5p0UaZsYWMn4L1dSpc6AhN,USSM11801303,2018-12-11
112,"A$AP Rocky, Skepta",Praise The Lord (Da Shine),2018-05-24,Universal Music New Zealand Limited,Australia,regional,113,297,6,24,2018-06-07,8,"30, 36, 32, 32, 33, 34, 33, 36, 46, 46, 44, 42...",7ycWLEP1GsNjVvcjawXz3z,"13ubrt8QOOCPljQ2FL1Kca, 2p1fiYHYiXz9qi0JJyxBzN",3MATDdrpHmQCmuOcozZjDa,USRC11800930,2017-11-17

In [32]:
##add new columns with new values
dfs['track_uri'] = dff['track_uri']
dfs['sp'] = dff['popularity_score']
dfs['ap'] = dff['artist_popularity']

dfs[:5]

,artist,track,r_date,label,country,chart_type,latest_pos,days_chart,freq,peak_pos,...,pos_chg,hist_pos,track_id,artist_id,album_id,isrc,release_date,track_uri,sp,ap
39,Ocean Alley,Confidence,2018-03-08,Oat Milk,Australia,regional,40,138,3,4,...,0,"117, 146, 154, 147, 132, 135, 147, 169, 185, 1...",7to68V64Cu6zk0UDo5tyw3,18lpwfiys4GtdHWNUu9qQr,0MVMsDS0kofp6A8cbJ5kSH,AUZN31700127,2018-12-11,spotify:track:67EUBsc4qosGOVbaYy6TeX,69.0,[72]
49,"Billie Eilish, Khalid",lovely - Bonus Track,2017-08-10,Sony Music UK,Australia,regional,50,102,7,29,...,-1,"45, 43, 40, 40, 38, 36, 37, 46, 50, 47, 46, 48...",1NJcg626wLln4pGHpiV7mf,"6qqNVTkY8uBg9cP3Jd7DAH, 6LuN9FCkKOj5PcnpouEgny",5YCdlD3eREt72lTZxNL7id,USUM71804190,2018-04-06,spotify:track:7ef4DlsgrMEH11cDZd32M6,82.0,"[89, 87]"
97,The Killers,Mr. Brightside,2003-12-31,Epic/Legacy,Australia,regional,98,985,6,47,...,11,"112, 115, 115, 135, 121, 121, 128, 124, 134, 1...",7oK9VyNzrYvRFo7nQEYkWN,0C0XlULifJtAgn6ZNCW2eu,4undIeGmofnAYKhnDclN1w,USIR20400274,2002,spotify:track:1UzofFX5AkfTDnwjcBkM4J,50.0,[59]
101,King Princess,1950,2018-02-22,Oat Milk,Australia,regional,102,365,2,13,...,-28,"149, 87, 86, 88, 100, 86, 84, 57, 57, 58, 66, ...",0CZ8lquoTX2Dkg7Ak2inwA,6beUvFUlKliUYJdLOXNj9C,5p0UaZsYWMn4L1dSpc6AhN,USSM11801303,2018-12-11,spotify:track:67EUBsc4qosGOVbaYy6TeX,69.0,[72]
112,"A$AP Rocky, Skepta",Praise The Lord (Da Shine),2018-05-24,Universal Music New Zealand Limited,Australia,regional,113,297,6,24,...,8,"30, 36, 32, 32, 33, 34, 33, 36, 46, 46, 44, 42...",7ycWLEP1GsNjVvcjawXz3z,"13ubrt8QOOCPljQ2FL1Kca, 2p1fiYHYiXz9qi0JJyxBzN",3MATDdrpHmQCmuOcozZjDa,USRC11800930,2017-11-17,spotify:track:5YOqfElMeshCt5oRk4yAgx,49.0,[62]

Drop all rows that have songs released prior to 2018-06-01

In [33]:
##make sure values in release_date column are datetype data type
dfs['release_date'] = pd.to_datetime(dfs['release_date']) 

##cutoff date
date = datetime.datetime(2018, 6, 1)

##mask to find which values have a release date late that the cutoff
time_mask = (dfs['release_date'] > date)

##apply mask to df
df_release = dfs[time_mask]
len(df_release)

28

Filter out off limits artists and labels

In [34]:
##uppercase artists and labels in df
col_upper(df_release, 'artist_upper', 'artist')
col_upper(df_release, 'label_upper', 'label')

##already have value lists of uppercase off limits labels and artists

##remove off limits values
df_release = remove_off_limits(df_release, artist_list, 'artist_upper')
df_release = remove_off_limits(df_release, label_list, 'label_upper')

##drop uppercase columns
df_release = df_release.drop(columns = ['artist_upper', 'label_upper'])

len(df_release)

/Users/elahshalev/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

27

Sort the dataframe by latest_pos ASC, days_chart DESC, then freq DESC

In [35]:
##set values in columns to integer data type
df_release['latest_pos'] = df_release['latest_pos'].astype(int)
df_release['days_chart'] = df_release['days_chart'].astype(int)
df_release['freq'] = df_release['freq'].astype(int)

##sort df
df_release = df_release.sort_values(['latest_pos', 'days_chart', 'freq'], ascending=[True, False, False])
df_release[:5]

,artist,track,r_date,label,country,chart_type,latest_pos,days_chart,freq,peak_pos,...,pos_chg,hist_pos,track_id,artist_id,album_id,isrc,release_date,track_uri,sp,ap
11,Absofacto,Dissolve,2017-11-02,Cub Sport Records,United States,viral,12,22,7,12,...,-1,"50, 33, 31, 25, 26, 25, 25, 24, 22, 25, 28, 27...",7pBrj5rt4SSxXwFKOyZfHR,7gAYvcQFmAruyvwGjxrSUr,79mdn7airf7jJw1dhV1PCI,USAT21704522,2019-01-18,spotify:track:2sqpbFR2bFI9nyJS5hqax1,47.0,[60]
11,Absofacto,Dissolve,2017-11-02,Cub Sport Records,New Zealand,viral,12,14,7,9,...,3,"42, 39, 38, 35, 38, 36, 47, 47, 45, 29, 20, 13...",7pBrj5rt4SSxXwFKOyZfHR,7gAYvcQFmAruyvwGjxrSUr,79mdn7airf7jJw1dhV1PCI,USAT21704522,2019-01-18,spotify:track:2sqpbFR2bFI9nyJS5hqax1,47.0,[60]
17,Absofacto,Dissolve,2017-11-02,1143852 Records DK,Global,viral,18,15,7,18,...,-2,"34, 44, 45, 45, 37, 33, 32, 30, 27, 26, 24, 22...",7pBrj5rt4SSxXwFKOyZfHR,7gAYvcQFmAruyvwGjxrSUr,79mdn7airf7jJw1dhV1PCI,USAT21704522,2019-02-12,spotify:track:0n7zjTSJOraGmjXfzTX6NL,43.0,[41]
22,Cavetown,Boys Will Be Bugs,2018-12-10,Oat Milk,Ireland,viral,23,6,6,23,...,-5,"47, 48, 50, 46, 28, 23",67EUBsc4qosGOVbaYy6TeX,2hR4h1Cao2ueuI7Cx9c7V8,1PKhm3GDDgOUwFbMEkZ89R,USL4Q1849675,2018-12-11,spotify:track:67EUBsc4qosGOVbaYy6TeX,69.0,[72]
31,They Might Be Giants,Istanbul,1990-01-01,Mogul Vision/Interscope Records,Australia,viral,32,23,5,22,...,1,"44, 30, 22, 23, 27, 26, 25, 30, 30, 31, 29, 29...",63vL5oxWrlvaJ0ayNaQnbX,6zB02lwP6L6ZH32nggQiJT,7FwAtuhhWivxvK4aPgyyUD,USEE10181576,2019-03-15,spotify:track:15AF6h7aQ0ibWzBbzAFLL9,57.0,[78]

Rearrange columns

In [36]:
df_release = df_release[['artist', 
'track', 
'r_date', 
'label', 
'sp', 
'ap', 
'country', 
'chart_type',
'latest_pos',
'days_chart', 
'freq', 
'peak_pos', 
'peak_date', 
'pos_chg', 
'hist_pos', 
'track_uri']]

Keep only first 20 rows

In [37]:
df_final = df_release[:20]
df_final

,artist,track,r_date,label,sp,ap,country,chart_type,latest_pos,days_chart,freq,peak_pos,peak_date,pos_chg,hist_pos,track_uri
11,Absofacto,Dissolve,2017-11-02,Cub Sport Records,47.0,[60],United States,viral,12,22,7,12,2019-03-16,-1,"50, 33, 31, 25, 26, 25, 25, 24, 22, 25, 28, 27...",spotify:track:2sqpbFR2bFI9nyJS5hqax1
11,Absofacto,Dissolve,2017-11-02,Cub Sport Records,47.0,[60],New Zealand,viral,12,14,7,9,2019-03-15,3,"42, 39, 38, 35, 38, 36, 47, 47, 45, 29, 20, 13...",spotify:track:2sqpbFR2bFI9nyJS5hqax1
17,Absofacto,Dissolve,2017-11-02,1143852 Records DK,43.0,[41],Global,viral,18,15,7,18,2019-03-16,-2,"34, 44, 45, 45, 37, 33, 32, 30, 27, 26, 24, 22...",spotify:track:0n7zjTSJOraGmjXfzTX6NL
22,Cavetown,Boys Will Be Bugs,2018-12-10,Oat Milk,69.0,[72],Ireland,viral,23,6,6,23,2019-03-16,-5,"47, 48, 50, 46, 28, 23",spotify:track:67EUBsc4qosGOVbaYy6TeX
31,They Might Be Giants,Istanbul,1990-01-01,Mogul Vision/Interscope Records,57.0,[78],Australia,viral,32,23,5,22,2019-02-24,1,"44, 30, 22, 23, 27, 26, 25, 30, 30, 31, 29, 29...",spotify:track:15AF6h7aQ0ibWzBbzAFLL9
31,Cavetown,Boys Will Be Bugs,2018-12-10,Mogul Vision/Interscope Records,57.0,[78],United States,viral,32,20,6,26,2019-03-08,3,"50, 43, 41, 42, 42, 41, 44, 43, 43, 40, 31, 26...",spotify:track:15AF6h7aQ0ibWzBbzAFLL9
39,Ocean Alley,Confidence,2018-03-08,Oat Milk,69.0,[72],Australia,regional,40,138,3,4,2019-01-27,0,"117, 146, 154, 147, 132, 135, 147, 169, 185, 1...",spotify:track:67EUBsc4qosGOVbaYy6TeX
39,"Billie Eilish, Khalid",lovely - Bonus Track,2017-08-10,Oat Milk,69.0,[72],New Zealand,regional,40,102,7,31,2019-02-05,-7,"38, 37, 37, 33, 32, 33, 36, 41, 43, 41, 42, 40...",spotify:track:67EUBsc4qosGOVbaYy6TeX
39,"Felix Cartal, LIGHTS",Love Me,2019-02-13,Oat Milk,69.0,[72],Canada,viral,40,5,1,39,2019-03-15,1,"49, 46, 40, 39, 40",spotify:track:67EUBsc4qosGOVbaYy6TeX
40,"The Doorbeen, Ragini",Lamberghini,2018-02-25,Physical Presents / Fontana North,65.0,"[65, 64]",Canada,viral,41,24,2,13,2019-02-21,-6,"15, 13, 13, 14, 18, 19, 20, 24, 24, 31, 31, 46...",spotify:track:53hNIcq8OLj9OUNvQ4ulFM
44,LocoCity,Job Done,2019-01-27,Bonsound,46.0,[46],Canada,viral,45,10,1,36,2019-03-06,-4,"44, 44, 40, 44, 36, 41, 47, 50, 49, 45",spotify:track:17RcMFZHPrjusBlklhSKou
45,They Might Be Giants,Istanbul,1990-01-01,WEA Latina,81.0,[88],United Kingdom,viral,46,19,5,28,2019-02-24,-2,"46, 30, 30, 28, 29, 29, 30, 29, 31, 33, 38, 35...",spotify:track:6FyRXC8tJUh863JCkyWqtk
45,"lil ricefield, seiji oda",Trapanese,2018-02-01,WEA Latina,81.0,[88],New Zealand,viral,46,2,1,39,2019-03-15,7,"39, 46",spotify:track:6FyRXC8tJUh863JCkyWqtk
48,They Might Be Giants,Istanbul,1990-01-01,House of Haze,82.0,"[94, 75]",Ireland,viral,49,24,5,22,2019-02-27,2,"41, 35, 30, 24, 23, 25, 22, 25, 27, 30, 38, 41...",spotify:track:1LiN0Z98FkR1t0m8KmLcAH
48,Dead Obies,Doo Wop,2019-02-14,House of Haze,82.0,"[94, 75]",Canada,viral,49,4,1,42,2019-03-15,7,"49, 45, 42, 49",spotify:track:1LiN0Z98FkR1t0m8KmLcAH
59,Luke Kelly,Raglan Road,2003-12-31,Hugoworld AS,67.0,[61],Ireland,regional,60,2,2,60,2019-03-16,-17,"77, 60",spotify:track:7B7O5jgFpWfc9orZw6FN4K
60,"Billie Eilish, Khalid",lovely - Bonus Track,2017-08-10,David Rees,67.0,[59],Canada,regional,61,101,7,46,2019-01-08,-13,"63, 80, 82, 58, 55, 54, 54, 65, 86, 89, 57, 65...",spotify:track:3VaFDR5FuLjgZxJ36hV9LN
62,"Billie Eilish, Khalid",lovely - Bonus Track,2017-08-10,"Duars Entertainment, Corp.",78.0,"[81, 93]",Ireland,regional,63,102,7,40,2019-02-04,5,"82, 90, 70, 63, 66, 65, 67, 86, 98, 77, 71, 82...",spotify:track:08aYFNUTIOMGq93e2VSArQ
101,King Princess,1950,2018-02-22,Oat Milk,69.0,[72],Australia,regional,102,365,2,13,2018-05-19,-28,"149, 87, 86, 88, 100, 86, 84, 57, 57, 58, 66, ...",spotify:track:67EUBsc4qosGOVbaYy6TeX
104,"Calvin Harris, Dua Lipa",One Kiss (with Dua Lipa),2018-04-05,NSG Entertainment,70.0,"[68, 69]",Ireland,regional,105,343,3,1,2018-04-13,-1,"6, 6, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...",spotify:track:2cytBOLpwFRX7J9URCrFIe

In [38]:
##export playlist
final_track_list = df_final['track_uri'].values.tolist()

##TODO: what is playlist id??
playlist = sp.user_playlist_create(USERNAME, 'Elektra Sample Playlist', public=True, description='')

playlist_id = playlist['id']

sp.user_playlist_add_tracks(USERNAME, playlist_id, final_track_list, position=None)

{u'snapshot_id': u'Myw1NzA5MmQyNGQyMjRkODY2OTIxZGIyYzA4M2Y4ODZhN2EzZDAyMmI0'}

In [43]:
df_final = df_final.reset_index()
df_final.to_excel('final_report.xlsx')

df_final[:1]

,level_0,index,artist,track,r_date,label,sp,ap,country,chart_type,latest_pos,days_chart,freq,peak_pos,peak_date,pos_chg,hist_pos,track_uri
0,0,11,Absofacto,Dissolve,2017-11-02,Cub Sport Records,47.0,[60],United States,viral,12,22,7,12,2019-03-16,-1,"50, 33, 31, 25, 26, 25, 25, 24, 22, 25, 28, 27...",spotify:track:2sqpbFR2bFI9nyJS5hqax1